labels:
  dependencies:
    color: "BFD4F2"
    description: Pull requests that update a dependency file
  # https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-default-labels
  good first issue:
    color: "7057ff"
    description: If you haven't contributed yet, this might be a good place to start
  help wanted:
    color: "008672"
    description: We can't figure this out, please help

  metadata:
    color: "EEEEEE"
    description: Relates to package metadata
  debian:
    color: "CE0056"
    description: Anything relating to Debian
  ubuntu:
    color: "E95420"
    description: Anything relating to Ubuntu
