name: Debian Security

on:
  schedule:
    # nightly at 3:00
    - cron: "3 0 * * *"
  workflow_dispatch:

concurrency:
  group: debian-security
  cancel-in-progress: true

jobs:
  metadata:
    name: Metadata
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    env:
      DEBIAN_MIRROR: security.debian.org
      DEBIAN_ROOT: debian-security
      DEBIAN_ARCHITECTURE: amd64
    strategy:
      fail-fast: false
      matrix:
        DEBIAN_RELEASE:
          - bookworm-security
          - bullseye-security
          - trixie-security
        DEBIAN_COMPONENT:
          - main
          - contrib
          - non-free
          - non-free-firmware
        exclude:
          - DEBIAN_RELEASE: bullseye-security
            DEBIAN_COMPONENT: non-free-firmware

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          repository: "apt-repositories/debian"
          token: ${{ secrets.GH_ORG_TOKEN }}

      - name: Select NodeJS version
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        env:
          # renovate: datasource=docker depName=node versioning=node
          NODE_VERSION: "20.12.2"
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Update metadata
        id: metadata
        env:
          DEBIAN_RELEASE: ${{ matrix.DEBIAN_RELEASE }}
          DEBIAN_COMPONENT: ${{ matrix.DEBIAN_COMPONENT }}
        run: |
          rm -rf apt/$DEBIAN_ROOT/$DEBIAN_RELEASE/$DEBIAN_COMPONENT || true

          set -o pipefail
          echo "log<<EOF" >> $GITHUB_OUTPUT
          npx --package @apt-repositories/generator --command generate "apt/$DEBIAN_ROOT/$DEBIAN_RELEASE/$DEBIAN_COMPONENT" | tee --append $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          set +o pipefail

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
          branch: "${{ env.DEBIAN_ROOT }}/${{ matrix.DEBIAN_RELEASE }}/${{ matrix.DEBIAN_COMPONENT }}"
          title: "chore(${{ env.DEBIAN_ROOT }}): ${{ matrix.DEBIAN_RELEASE }}/${{ matrix.DEBIAN_COMPONENT }}"
          labels: |
            metadata
            ${{ matrix.DEBIAN_RELEASE }}
          body: |
            ## Metadata Log
            ```shell
            ${{ steps.metadata.outputs.log }}
            ```
          commit-message: |
            chore(${{ env.DEBIAN_ROOT }}): Metadata update for ${{ matrix.DEBIAN_RELEASE }}/${{ matrix.DEBIAN_COMPONENT }}

            Generated at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Enable Pull Request Automerge
        if: ${{ steps.pr.outputs.pull-request-number }}
        run: gh pr merge --merge --auto "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GH_ORG_TOKEN }}
